clang-cl: ThreadSafetyAnalysis.h: explicitly mark as external header.
clang-cl does not support -isystem, i guess to mimic the cl.exe
weaknesses, thus:

C:\darktable\rawspeed\src\external\ThreadSafetyAnalysis.h(11,9): error : macro name is a reserved identifier [-Werror,-Wreserved-id-macro]
  #define THREAD_ANNOTATION_ATTRIBUTE__(x) __attribute__((x))
          ^

Since that header is copied verbatim from the link at the top,
let's just mark it as external, and not s/__$/_/

It will be oh so much more noisy with all the other external deps :)
(gtest, gbench, all the buildable in-tree deps (jpeg, pugixml, zlib))

Based on a patch by Tobias Ellinghaus.