VC5Decompressor: clang-tidy temporaily bump readability-function-size limits
Eeek.
But hurray, those were all the clang-tidy warnings as of now.

$ clang-tidy -p ./ ../src/librawspeed/decompressors/VC5Decompressor.cpp
7240 warnings generated.
/home/lebedevri/rawspeed/src/librawspeed/decompressors/VC5Decompressor.cpp:186:32: error: function 'reconstructLowband' exceeds recommended size/complexity thresholds [readability-function-size,-warnings-as-errors]
void VC5Decompressor::Wavelet::reconstructLowband(
                               ^
/home/lebedevri/rawspeed/src/librawspeed/decompressors/VC5Decompressor.cpp:186:32: note: 168 lines including whitespace and comments (threshold 167)
/home/lebedevri/rawspeed/src/librawspeed/decompressors/VC5Decompressor.cpp:403:23: error: function 'decode' exceeds recommended size/complexity thresholds [readability-function-size,-warnings-as-errors]
void VC5Decompressor::decode(const unsigned int offsetX,
                      ^
/home/lebedevri/rawspeed/src/librawspeed/decompressors/VC5Decompressor.cpp:403:23: note: 259 lines including whitespace and comments (threshold 167)
/home/lebedevri/rawspeed/src/librawspeed/decompressors/VC5Decompressor.cpp:403:23: note: 224 statements (threshold 136)
/home/lebedevri/rawspeed/src/librawspeed/decompressors/VC5Decompressor.cpp:403:23: note: 43 branches (threshold 26)
/home/lebedevri/rawspeed/src/librawspeed/decompressors/VC5Decompressor.cpp:539:40: note: nesting level 7 starts here (threshold 6)
            for (; count > 0; --count) {
                                       ^
/home/lebedevri/rawspeed/src/librawspeed/decompressors/VC5Decompressor.cpp:403:23: note: 45 variables (threshold 30)
void VC5Decompressor::decode(const unsigned int offsetX,
                      ^