BitStreamerJPEG: add name to friend function's argument
dt's Fedora 38 PPC64LE build (and only that one?!)
is failing with a very weird
```
[  337s] In file included from /home/abuild/rpmbuild/BUILD/darktable-4.7.0~git534.af89bfbf/src/external/rawspeed/src/librawspeed/decoders/../decompressors/SonyArw1Decompressor.h:25,
[  337s]                  from /home/abuild/rpmbuild/BUILD/darktable-4.7.0~git534.af89bfbf/src/external/rawspeed/src/librawspeed/decoders/ArwDecoder.cpp:35:
[  337s] /home/abuild/rpmbuild/BUILD/darktable-4.7.0~git534.af89bfbf/src/external/rawspeed/src/librawspeed/decoders/../io/BitStreamerMSB.h:47:29: error: default argument specified in explicit specialization [-fpermissive]
[  337s]    47 |   friend void Base::fill(int); // Allow it to call our `fillCache()`.
[  337s]       |                             ^
[  338s] gmake[2]: *** [lib64/darktable/rawspeed/src/librawspeed/decoders/CMakeFiles/rawspeed_decoders.dir/build.make:93:
```
... which makes zero sense since we clearly don't have
a default argument here. Maybe giving it a name helps?
Probably not.