GCC: disable `-Wmaybe-uninitialized`
```
build-GCC13-release$ /usr/bin/g++-13 -DNDEBUG -I/home/lebedevri/rawspeed/build-GCC13-release/src -I/home/lebedevri/rawspeed/src/librawspeed/decoders/.. -isystem /home/lebedevri/rawspeed/src/external -Wall -Wextra -Wcast-qual -Wextra -Wextra-semi -Wformat=2 -Wpointer-arith -Wvla -Wmissing-format-attribute -Wsuggest-attribute=format -Wno-unused-parameter -Wno-stringop-overflow -Wno-array-bounds -Wstack-usage=4096 -Wframe-larger-than=4096 -Wlarger-than=32768 -Werror -O3 -DNDEBUG -O3 -std=c++20 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -march=native -g3 -ggdb3 -fopenmp -MD -MT src/librawspeed/decoders/CMakeFiles/rawspeed_decoders.dir/Cr2Decoder.cpp.o -MF src/librawspeed/decoders/CMakeFiles/rawspeed_decoders.dir/Cr2Decoder.cpp.o.d -o src/librawspeed/decoders/CMakeFiles/rawspeed_decoders.dir/Cr2Decoder.cpp.o -c /home/lebedevri/rawspeed/src/librawspeed/decoders/Cr2Decoder.cpp
In function ‘rawspeed::Optional<std::pair<rawspeed::{anonymous}::ColorDataFormat, rawspeed::Optional<int> > > rawspeed::{anonymous}::deduceColorDataFormat(const rawspeed::TiffEntry*)’,
    inlined from ‘bool rawspeed::Cr2Decoder::decodeCanonColorData() const’ at /home/lebedevri/rawspeed/src/librawspeed/decoders/Cr2Decoder.cpp:389:35:
/home/lebedevri/rawspeed/src/librawspeed/decoders/Cr2Decoder.cpp:246:46: error: ‘((int*)((char*)&<unnamed> + offsetof(rawspeed::Optional<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> > >,rawspeed::Optional<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> > >::impl.std::optional<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> > >::<unnamed>.std::_Optional_base<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> >, true, true>::_M_payload.std::_Optional_payload<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> >, true, false, false>::<unnamed>.std::_Optional_payload_base<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> > >::_M_payload)))[1]’ may be used uninitialized [-Werror=maybe-uninitialized]
  246 |     return {{ColorDataFormat::ColorData1, {}}};
      |                                              ^
/home/lebedevri/rawspeed/src/librawspeed/decoders/Cr2Decoder.cpp: In member function ‘bool rawspeed::Cr2Decoder::decodeCanonColorData() const’:
/home/lebedevri/rawspeed/src/librawspeed/decoders/Cr2Decoder.cpp:246:46: note: ‘<anonymous>’ declared here
  246 |     return {{ColorDataFormat::ColorData1, {}}};
      |                                              ^
In function ‘rawspeed::Optional<std::pair<rawspeed::{anonymous}::ColorDataFormat, rawspeed::Optional<int> > > rawspeed::{anonymous}::deduceColorDataFormat(const rawspeed::TiffEntry*)’,
    inlined from ‘bool rawspeed::Cr2Decoder::decodeCanonColorData() const’ at /home/lebedevri/rawspeed/src/librawspeed/decoders/Cr2Decoder.cpp:389:35:
/home/lebedevri/rawspeed/src/librawspeed/decoders/Cr2Decoder.cpp:249:46: error: ‘((int*)((char*)&<unnamed> + offsetof(rawspeed::Optional<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> > >,rawspeed::Optional<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> > >::impl.std::optional<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> > >::<unnamed>.std::_Optional_base<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> >, true, true>::_M_payload.std::_Optional_payload<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> >, true, false, false>::<unnamed>.std::_Optional_payload_base<std::pair<rawspeed::<unnamed>::ColorDataFormat, rawspeed::Optional<int> > >::_M_payload)))[1]’ may be used uninitialized [-Werror=maybe-uninitialized]
  249 |     return {{ColorDataFormat::ColorData2, {}}};
      |                                              ^
/home/lebedevri/rawspeed/src/librawspeed/decoders/Cr2Decoder.cpp: In member function ‘bool rawspeed::Cr2Decoder::decodeCanonColorData() const’:
/home/lebedevri/rawspeed/src/librawspeed/decoders/Cr2Decoder.cpp:249:46: note: ‘<anonymous>’ declared here
  249 |     return {{ColorDataFormat::ColorData2, {}}};
      |                                              ^

```